### ISSUE TITLE
Auto-Reload not working

### ISSUE THREAD

**Issue by darkyen** [phonegap/connect-phonegap#119]
I use a gulp task to build the files and then `phonegap serve` to serve them, it used to work before /appzip but now it doesn't. It detects files as changed but never updates the developer app.

**Comment by darkyen** [comment]
My bad, cordova.js was not linked properly, i wonder though why is it required for the cordova.js to poll the server ? Why can't a dev script be injected into the index.html or some other server side only measure ?

**Comment by mwbrooks** [comment]
Hi @darkyen,

Glad you figured out the issue. We're working through some of the shortcomings of the `/appzip` approach. It's solved a major CORS issue but introduced some annoyances in performance.

We actually do inject the polling logic into all HTML files. However, I've noticed that it listens for `deviceready` rather than the `load` event, before initializing. I think your suggestion of using the DOM `load` event is more flexible without any drawbacks, so I'll create an issue to update that.

**Comment by darkyen** [comment]
One more way could be using diffs ? After the appzip is sent only send the updated files, hot replace and reload them ?

**Comment by mwbrooks** [comment]
Yea, we've been calling that approach "delta updates." We definitely want
that to land, but decided to do an early release to ensure there were no
major issues (and we have found a few).
