### ISSUE TITLE
Silent failure when running phonegap serve

### ISSUE THREAD

**Issue by gabrielstuff** [phonegap/connect-phonegap#139]
Trying this new toy and running : `phonegap serve`, I've been serve the following message : 

```
[phonegap] starting app server...
[phonegap] listening on 192.168.0.15:3000
[phonegap]
[phonegap] ctrl-c to stop the server
[phonegap]
```

This is totally fake :) as I have multiple server already running on 3000 / 3001 / 3002

I had to force on 3003 to make it really run and be able to connect from my iPhone : 
`phonegap serve --port 3003`

and then : 

```
[phonegap] starting app server...
[phonegap] listening on 192.168.0.15:3003
[phonegap]
[phonegap] ctrl-c to stop the server
[phonegap]
[phonegap] 200 /__api__/appzip
```

Maybe the server should try various port or simply fail and ask the user for an other port.

**Comment by mwbrooks** [comment]
Hmm... it's actually the legit address and port used by the server. On my machine, I receive an error that the port is in use when I try to run the server on `3000` when it's used by another process.

Are you on Windows or OS X? I'd like to recreate this error, because it could be the source of a deeper problem that we've seen where some people cannot connect to the server.

Thanks for submitting the issue with this kinda detail!

**Comment by gabrielstuff** [comment]
Hi !
I'm on OSX `10.10.5 (14F27)`. I'm using the pre-latest version of XCode as I did not get the time to update everything again :)

I'm using node `v4.1.0` with nvm `0.17.2` and npm `2.14.3`. I'm using phonegap `5.3.6`

hope it helps ! (any verbose ways to run it ? I could check but no time right now)

**Comment by filmaj** [comment]
@gabrielstuff you can run `phonegap -d serve` to get a more verbose mode.

I am closing this one down as it has been inactive for a while. If it still an issue, feel free to re-open and we can investigate further.
