### ISSUE TITLE
Getting 404 response in console on first attempt trying to download app

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/connect-phonegap#141]
When using PG Dev App, getting a 404 response in the console on the first attempt to download the app, but on the second attempt app is successfully found.

phonegap: 5.3.8
node: 5.0.0
npm: 3.3.6

**Comment by mwbrooks** [comment]
@surajpindoria does this happen with the production PG Dev App as well?

**Comment by surajpindoria** [comment]
@mwbrooks No, I am only seeing this with the updated content-sync plugin

**Comment by mwbrooks** [comment]
Ok, I know there are some issues with the latest `content-sync` plugin. I'd lean on it being the source of the problem and not `connect-phonegap`, which hasn't changed for a number of releases.

**Comment by surajpindoria** [comment]
Yeah maybe, Tim told me to file it here just so we can track it

**Comment by mwbrooks** [comment]
Cool!

**Comment by timkim** [comment]
Ok, I figured out the cause of this error. The ios content sync plugin has a check to see if the url is actually reachable so it pings the server here: 
https://github.com/phonegap/phonegap-plugin-contentsync/blob/master/src/ios/ContentSync.m#L142

Note the method request is `HEAD`. 

In our `zip` middleware, we have a check to see if the url end point matches `appzip` AND a `GET` http request:
https://github.com/phonegap/connect-phonegap/blob/master/lib/middleware/zip.js#L27

So really we need to just add a check for a `HEAD` request and 200 it. 

Interestingly, even though we've 404ing - the ios content sync plugin thinks everything is ok because it see the server responds but not actually trigger an error callback. What the ios content sync plugin needs to do is also check the response text is 200.
