### ISSUE TITLE
update template if it's old

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/connect-phonegap#148]
I've been having issues when using phonegap desktop app, the app created has an old template (doesn't happen if I create the app using phonegap or cordova CLI). 
I've been tracking down the problem and it seems to be here, on connect-phonegap. 

> phonegap.create(options)
> 
> The project is created from the same app template used by the PhoneGap CLI and Cordova CLI. When a template does not exist, it is fetched and saved in the common directory:
> 
> ~/.cordova/lib/www/phonegap/VERSION/

I went to the ~/.cordova/lib/www/phonegap/master/ folder and bingo, that's the app I'm getting when I create the app with Phonegap Desktop. Files are from 2014, so it's very very old.

So, on https://github.com/phonegap/connect-phonegap/blob/master/lib/create.js, the fetchTemplate method should check if the template is old and update it.

**Comment by surajpindoria** [comment]
`phonegap.create` in connect-phonegap was primarily for the PhoneGap Desktop App. We have now removed this functionality from connect and rely on the create within the PhoneGap CLI. The CLI, which just delegates to Cordova, should be pulling the latest version of the template if a version is not specified. Therefore I don't believe that this issue is relevant anymore.

If you are still seeing this, we should file it in https://github.com/phonegap/phonegap-cli.
